/* ==========================================================================
   商務談判協商知識庫 — 全站跨書／跨簡報頁深層檢索索引庫 (search-index.js)
   撰寫原則：整潔 (Clean) · 精準 (Precise) · 專業 (Professional)
   適用對象：Level 1 入門基礎 ➔ Level 2 進階實戰 ➔ Level 3 高階破局
   ========================================================================== */

window.NEGOTIATION_PORTAL_DATA = {
  portalMeta: {
    title: "商務談判協商知識庫暨麥肯錫簡報教材門戶",
    version: "R2.0 (2026-09)",
    system: "專業管理學院 ▸ 商務談判與協商策略知識庫",
    targetBooksCapacity: 50
  },

  /* 書籍與課程教材總表 (支援六大領域篩選與未來 50+ 本擴充) */
  books: [
    {
      id: "course-001",
      code: "COURSE #001",
      status: "published",
      domain: "framework price terms value defense posture",
      domainLabel: "01 核心框架與三層模型（L1–L3 全覆蓋）",
      title: "《有效提升你的談判能力：解決「我要」問題的實戰體系》",
      author: "湯君健（前寶潔 P&G 銷售部渠道總監、大型電商企業大學校長）",
      year: "2026 麥肯錫簡報首發",
      slidesCount: 16,
      exhibitsCount: 16,
      tablesCount: 16,
      actionsCount: 13,
      url: "course-tang-junjian-negotiation.html",
      pptxUrl: "downloads/tang-junjian-negotiation-mckinsey-briefing.pptx",
      thesis: "談判是運用決策中的理性與非理性因素，「以己方目標為先」，與對手聯手共創解決方案的過程。本教材透過「價格談判（分配博弈）→ 條件談判（多維交換）→ 價值談判（納入第三方把餅做大）」三層動態模型，結合內在心理防禦與外在語言姿態兩道防線，協助入門至進階學員實現利益與尊重兼得。",
      tags: [
        "解決我要問題",
        "分橘子冰山模型",
        "以己方目的為先",
        "價格談判",
        "條件談判",
        "價值談判",
        "機會成本底線",
        "供應鏈成本拆解",
        "報完價立刻閉嘴",
        "離桌威脅判讀",
        "遞減讓步原則",
        "條件換條件",
        "假設性提問",
        "最佳可替代方案",
        "價值鏈三角形",
        "拍板人評估人執行人",
        "離桌底氣",
        "五大心理戰防禦",
        "破解紅白臉",
        "標準拒絕公式",
        "誠懇堅定柔軟",
        "談判前一頁紙"
      ]
    },
    {
      id: "case-n01",
      code: "PLAYBOOK #N01",
      status: "published",
      domain: "value terms",
      domainLabel: "04 價值創造與組織決策（Level 3 高階）",
      title: "《B2B 複雜合約談判：三層談判模型 × MEDDIC 顧問式銷售協同》",
      author: "專業管理學院・B2B 商務實戰整合教案",
      year: "2026 實戰整合版",
      slidesCount: 2,
      exhibitsCount: 2,
      tablesCount: 2,
      actionsCount: 5,
      url: "course-tang-junjian-negotiation.html#slide-15",
      thesis: "將「一核心、三層循環、兩道防線」落地於 B2B 策略採購與大客戶銷售合約：當單價卡關時主動切換至條件層（付款期程、保固、交期），或納入第三方（終端客戶、通路、金融機構）做大價值鏈三角形，並對齊 MEDDIC 的經濟決策者（EB）、內部擁護者（Champion）與量化指標（Metrics）。",
      tags: ["B2B合約", "採購議價", "大客戶銷售", "MEDDIC整合", "談判前一頁紙", "八條邏輯因果鏈", "三級條款清單"]
    },
    {
      id: "book-002",
      code: "BOOK #002",
      status: "upcoming",
      domain: "framework terms",
      domainLabel: "01 核心框架與三層模型（Level 1–2）",
      title: "《哈佛談判課：談判力（Getting to Yes）》",
      author: "羅傑·費雪（Roger Fisher）、威廉·尤瑞（William Ury）｜哈佛談判專案",
      year: "候選教材佇列",
      slidesCount: 15,
      exhibitsCount: 15,
      tablesCount: 15,
      actionsCount: 20,
      url: "course-tang-junjian-negotiation.html#slide-09",
      thesis: "原則式談判四大支柱：① 把人與事分開（對事不對人）；② 聚焦利益而非立場（區分表面訴求與真實需求）；③ 構思互利選項；④ 堅持客觀標準（市場行情尺子），並以 BATNA（談判協議最佳替代方案）確立離桌底氣。",
      tags: ["哈佛談判課", "原則式談判", "BATNA", "對事不對人", "聚焦利益而非立場", "客觀標準"]
    },
    {
      id: "book-003",
      code: "BOOK #003",
      status: "upcoming",
      domain: "defense posture",
      domainLabel: "05 談判心態與心理防禦（Level 2–3）",
      title: "《絕不妥協：FBI 首席談判專家教你贏得任何談判（Never Split the Difference）》",
      author: "克里斯·沃斯（Chris Voss，前 FBI 國際人質談判首席專家）",
      year: "候選教材佇列",
      slidesCount: 16,
      exhibitsCount: 16,
      tablesCount: 16,
      actionsCount: 24,
      url: "course-tang-junjian-negotiation.html#slide-07",
      thesis: "反對平庸的「折衷切半」：運用戰術同理心（Tactical Empathy）、鏡像重複（Mirroring）、情緒標註（Labeling）、阿克曼議價模型（65%→85%→95%→100% 遞減讓步）與校準型問題掌握談判控場權。",
      tags: ["絕不妥協", "Chris Voss", "FBI談判", "戰術同理心", "阿克曼模型", "遞減讓步", "校準型問題"]
    },
    {
      id: "book-004",
      code: "BOOK #004",
      status: "upcoming",
      domain: "terms value",
      domainLabel: "03 條件交換與籌碼設計（Level 1–2）",
      title: "《沃頓商學院最受歡迎的談判課（Getting More）》",
      author: "史チュアート·戴蒙德（Stuart Diamond，沃頓商學院名師）",
      year: "候選教材佇列",
      slidesCount: 15,
      exhibitsCount: 15,
      tablesCount: 15,
      actionsCount: 20,
      url: "course-tang-junjian-negotiation.html#slide-08",
      thesis: "以目標為最高導向（以己方目的為先）：挖掘對方腦中的畫面與真實顧慮，執行「己方低成本 × 對方高價值」的不等價交換，將巨大分歧拆解為漸進式共識。",
      tags: ["沃頓商學院談判課", "Stuart Diamond", "不等價交換", "目標導向", "條件交換"]
    },
    {
      id: "book-005",
      code: "BOOK #005",
      status: "upcoming",
      domain: "price defense",
      domainLabel: "02 價格博弈與報價策略（Level 2）",
      title: "《優勢談判（Secrets of Power Negotiating）》",
      author: "羅傑·道森（Roger Dawson，國際商業談判專家）",
      year: "候選教材佇列",
      slidesCount: 16,
      exhibitsCount: 16,
      tablesCount: 16,
      actionsCount: 22,
      url: "course-tang-junjian-negotiation.html#slide-06",
      thesis: "價格博弈實戰法則：高報價錨定效應、絕不接受首次報價、聞價色變（Flinch）、扮演不情願的買賣方、更高權威原則（請示主管）以及拆解紅白臉陷阱。",
      tags: ["優勢談判", "Roger Dawson", "開高價錨定", "不情願讓步", "更高權威", "紅白臉應對"]
    }
  ],

  /* 逐頁簡報全索引 (支援全站關鍵字即時檢索、螢光高亮與一鍵直達) */
  slides: [
    {
      bookId: "course-001",
      bookTitle: "《有效提升你的談判能力》湯君健",
      slideNum: 1,
      slideId: "slide-01",
      layer: "overview",
      chapter: "發刊詞 ｜ 核心定義與專家特質（Level 1 入門｜版型 7：比較論法）",
      title: "① 主張：談判是幫你解決「我要」的問題——運用決策中的理性與非理性因素，以己方目標為先並與對手聯手共創方案",
      keywords: "版型7 比較論法 無雜訊簡報 發刊詞 湯君健 我要的問題 利益衝突 資源有限 零和分配 吵架 軟柿子 無端妥協 理性與非理性 以己方目的為先 聯手找到解決方案 可靠 原則性強 守信 寶潔 渠道總監 電商企業大學校長 甲方 乙方 入門基礎",
      summary: "【無雜訊版型 7：比較論法】比較缺乏談判能力的兩極失敗誤區（衝突爭吵 vs. 佛系軟柿子），於中央交集確立「解決我要問題 × 可靠特質（守原則、重信譽、專注找方案、換位思考）」。",
      action: "盤點並寫下本季 3 項「我要但不易直接取得」的關鍵目標（對客戶、對供應商、對內部跨部門各一項），作為實戰演練標的。",
      url: "course-tang-junjian-negotiation.html#slide-01"
    },
    {
      bookId: "course-001",
      bookTitle: "《有效提升你的談判能力》湯君健",
      slideNum: 2,
      slideId: "slide-02",
      layer: "overview",
      chapter: "全課架構 ｜ 一核心、三層循環、兩道防線（Level 1–3｜版型 3：結合論法）",
      title: "① 結論：以「我要」為核心，透過「外部業務突破三層次」與「內部能力底盤雙防線」同時成立，構建雙贏談判系統",
      keywords: "版型3 結合論法 金字塔支撐樹 無雜訊簡報 全課架構 一核心 三層循環 兩道防線 價格談判 條件談判 交換類談判 價值談判 心態 心理戰 語言 肢體語言 循環模型 作戰階段對照表",
      summary: "【無雜訊版型 3：結合論法】頂層結論（解決我要問題的雙贏閉環）由兩大主要素同時支撐：外部業務突破三層次（L1價格→L2條件→L3價值）＋內部能力底盤雙防線（第5講心態防線＋第6講語言防線）。",
      action: "在進入商務協商前，先以「三層模型」診斷當前談判所處維度，並利用「談判前一頁紙」完成全方位備戰。",
      url: "course-tang-junjian-negotiation.html#slide-02"
    },
    {
      bookId: "course-001",
      bookTitle: "《有效提升你的談判能力》湯君健",
      slideNum: 3,
      slideId: "slide-03",
      layer: "foundation",
      chapter: "第 1 講（上）表面訴求 vs 真實需求（Level 1 入門｜版型 6：對立論法）",
      title: "① 主張：表面訴求不等於真實需求——堅守「以己方目的為先」，透過資訊交換與加工挖掘對方的「橘子皮」",
      keywords: "版型6 對立論法 正反對照 無雜訊簡報 分橘子 冰山模型 橘子皮 小橘燈 橘子肉 橘子汁 表面訴求 真實需求 三要點 以己方目的為先 向前爭取 理性與非理性 7項準備清單 座位安排 靠牆 靠門 壓迫感 資訊交換 資訊加工 潛台詞",
      summary: "【無雜訊版型 6：對立論法】沿四大維度正反對照「見解 A：困在表面訴求（零和死局）」與「見解 B：穿透真實需求（分橘子皮肉分離，100% 雙贏）」，併用理性與非理性 7 項準備清單。",
      action: "會前拆解對手的「表面立場」與「背後真實用途（橘子皮）」，並將對手性格與主客座位配置納入準備流程。",
      url: "course-tang-junjian-negotiation.html#slide-03"
    },
    {
      bookId: "course-001",
      bookTitle: "《有效提升你的談判能力》湯君健",
      slideNum: 4,
      slideId: "slide-04",
      layer: "foundation",
      chapter: "第 1 講（下）三種基本模型與跨層切換（Level 1–2｜版型 5：麥肯錫論法）",
      title: "① 主張：複雜談判皆可拆解為三種基本模型——先辨識所處層次，並在卡關時主動推動談判跨層升級",
      keywords: "版型5 麥肯錫論法 流程診斷矩陣 無雜訊簡報 三種基本模型 價格談判 零和博弈 條件談判 付款方式 交期 良率 各取所需 價值談判 創造新價值 孩子看電視 跨層切換 外事人員標準13條 美國國務院 外交官",
      summary: "【無雜訊版型 5：麥肯錫論法】橫軸展開「價格類→條件類→價值類」三階段演進流程，縱軸拆解各階段之「僵局診斷信號」與「跨層破局解方」，把餅做大後回歸價格層完成分配。",
      action: "檢視近期進行中的商務協商，診斷其目前處於價格、條件或價值哪一層，並規劃跨層升級方案。",
      url: "course-tang-junjian-negotiation.html#slide-04"
    },
    {
      bookId: "course-001",
      bookTitle: "《有效提升你的談判能力》湯君健",
      slideNum: 5,
      slideId: "slide-05",
      layer: "price",
      chapter: "第 2 講（上）機會成本底線與成本拆解（Level 1–2｜版型 1：一對一論法）",
      title: "① 主張：善戰者立於不敗之地——以機會成本設定底線、以市場尺子錨定目標，並拆解供應鏈成本鎖定 32% 議價水分",
      keywords: "版型1 一對一論法 單一強證據 無雜訊簡報 價格談判 準備階段 底線價 心理最低價 機會成本 目標價 市場尺子 二手車 真正懂行 零售巨頭 首席商品官 紅酒採購 成本拆解 Should-Cost 孫子兵法 善戰者立於不敗之地 薪資基數",
      summary: "【無雜訊版型 1：一對一論法】單一強證據成本拆解長條圖：將直接原料、人工、研發、物流 4 項剛性成本設為灰階基準，唯獨焦點「32% 銷售與超額毛利水分」以琥珀金高亮，並以機會成本鎖定底線。",
      action: "橫向比對 5 家以上供應商報價單，拆解原材料、加工、物流與毛利結構，並在會前書面確立底線價與目標價。",
      url: "course-tang-junjian-negotiation.html#slide-05"
    },
    {
      bookId: "course-001",
      bookTitle: "《有效提升你的談判能力》湯君健",
      slideNum: 6,
      slideId: "slide-06",
      layer: "price",
      chapter: "第 2 講（中）報價先後手與沉默鐵律（Level 2 進階｜版型 8：BCG 論法）",
      title: "① 主張：依「資訊對稱度 × 開價策略」2×2 矩陣決定先後手，並嚴格執行「報完價立刻閉嘴」沉默鐵律",
      keywords: "版型8 BCG論法 BCG矩陣 2x2矩陣 無雜訊簡報 誰先報價 資訊不對稱 後出價 掌握行情 先報價 錨定效應 高報價 還價空間 五星飯店 會務銷售 給面子 合理報價 報價理由 報完價立刻閉嘴 沉默 察言觀色 心虛解釋",
      summary: "【無雜訊版型 8：BCG 2×2 矩陣】以資訊掌握度（X軸）與開價策略（Y軸）定位四象限：資訊充分時鎖定右上黃金象限「精準先手錨定＋報完價立刻閉嘴」；資訊不足時採左下「誘敵後手拆解」。",
      action: "為下一筆關鍵報價預先寫妥 3 條客觀理由，並在會議中報出數字後強制默數 5 秒不發一言。",
      url: "course-tang-junjian-negotiation.html#slide-06"
    },
    {
      bookId: "course-001",
      bookTitle: "《有效提升你的談判能力》湯君健",
      slideNum: 7,
      slideId: "slide-07",
      layer: "price",
      chapter: "第 2 講（下）離桌威脅判讀與遞減讓步（Level 2 進階｜版型 4：連鎖論法）",
      title: "① 主張：從「具體使用場景挑刺」識破假離桌威脅，並遵循「幅度遞減、節奏放緩」四步連鎖法則讓步",
      keywords: "版型4 連鎖論法 因果時間軸 無雜訊簡報 還價 拆解依據 離桌威脅 假離桌 真離桌 具體使用場景 非硬傷 房間擺床 座椅靠背 一言不發 讓步三紀律 不一步到位 不情願的讓步者 幅度遞減 先讓50再讓80 得寸進尺",
      summary: "【無雜訊版型 4：連鎖論法】展開四輪遞減讓步因果序列（-6% → -3% → -1% → -0.45% 精確尾數封頂），傳遞底線枯竭信號；並從對手挑刺是否具「具體使用場景」判讀假離桌威脅。",
      action: "會前預先規劃 4 次遞減讓步階梯（如 6% → 3% → 1% → 0.45%），並觀察對手挑刺是否具備具體使用場景以判讀成交意願。",
      url: "course-tang-junjian-negotiation.html#slide-07"
    },
    {
      bookId: "course-001",
      bookTitle: "《有效提升你的談判能力》湯君健",
      slideNum: 8,
      slideId: "slide-08",
      layer: "terms",
      chapter: "第 3 講（上）條款三級分類與假設提問（Level 2 進階｜版型 2：並列論法）",
      title: "① 主張：「條款列得多」等同價格開得高——將可談條件並列分為三級目標，並以「如果…就…」假設提問刺探優先序",
      keywords: "版型2 並列論法 同構卡片 無雜訊簡報 條件談判 條款三級分類 商鋪租賃 20項清單 主要目標 次要目標 底線條件 非正式會議 吹風會 需求確認類問題 優先級排序 假設性問題 二選一 期權 薪資 傾聽原則",
      summary: "【無雜訊版型 2：並列論法】將合約條款並列分為三欄同構等級：等級 1 重要條款（紅線）、等級 2 次要條款（主力交換籌碼★）、等級 3 無關緊要條款（順水人情），結合吹風會與假設提問測試交換空間。",
      action: "將標準商務合約拆解為 15～20 項條款並完成三級標註；會前準備 2 道二選一假設題以測試對手真實偏好。",
      url: "course-tang-junjian-negotiation.html#slide-08"
    },
    {
      bookId: "course-001",
      bookTitle: "《有效提升你的談判能力》湯君健",
      slideNum: 9,
      slideId: "slide-09",
      layer: "terms",
      chapter: "第 3 講（下）最佳可替代方案與條件交換（Level 2 進階｜版型 7：比較論法）",
      title: "① 主張：以己方低成本條件換取對方高價值讓步——尋找優於談崩的最佳可替代方案 (BATNA)，並嚴守「條件換條件」原則",
      keywords: "版型7 比較論法 文氏圖交集 無雜訊簡報 最佳可替代方案 顧慮替換法 名貴木桌 隱藏可替代方案 BATNA 談崩退路 不等價交換 讓步三原則 次要目標讓步 以退為進 不情願讓步 更高權威 條件換條件 付三押三 換新空調 防禦緩衝帶",
      summary: "【無雜訊版型 7：比較論法】比較甲方與乙方的差異化低成本籌碼（兩側差異點），於中央交集透過 BATNA 槓桿與「條件換條件」防禦緩衝帶達成不等價雙贏互換。",
      action: "每次被迫讓步時務必掛鉤一項新條件作為「防禦緩衝帶」（例：單價降 2% 可以，但預付款須提高至 30%）。",
      url: "course-tang-junjian-negotiation.html#slide-09"
    },
    {
      bookId: "course-001",
      bookTitle: "《有效提升你的談判能力》湯君健",
      slideNum: 10,
      slideId: "slide-10",
      layer: "value",
      chapter: "第 4 講（上）價值鏈三角形與增量破局（Level 3 高階｜版型 3：結合論法）",
      title: "① 結論：僵局是價值談判的最佳入口——透過「重構價值鏈三角形」與「引入第三方增量資源」擴大總利潤面積",
      keywords: "版型3 結合論法 演繹樹 無雜訊簡報 價值談判 創造新價值 僵局破冰 手機採購 10元價差 總利潤額 利潤率 女性顧客 女性專屬手機 流量購物節 閱讀價值鏈 第三方 終端顧客 價值鏈三角形 求職談薪",
      summary: "【無雜訊版型 3：結合論法】頂層高階結論（從分蛋糕躍升為做大蛋糕）由兩大主要素同時支撐：①重構「我方—對方—對方終端客戶」價值鏈三角形；②引入異業流量與跨期對賭資源。",
      action: "挑選一項價格卡關的合作專案，繪製納入終端顧客或金融機構之「價值鏈三角形」，並試算增量收益空間。",
      url: "course-tang-junjian-negotiation.html#slide-10"
    },
    {
      bookId: "course-001",
      bookTitle: "《有效提升你的談判能力》湯君健",
      slideNum: 11,
      slideId: "slide-11",
      layer: "value",
      chapter: "第 4 講（下）順風車提案與決策三角色（Level 3 高階｜版型 5：麥肯錫論法）",
      title: "① 主張：把己方方案「塞進對方的主張裡」——以量化數據、A/B/C 三選項與決策鏈三角色矩陣精準攻克組織決策",
      keywords: "版型5 麥肯錫論法 角色矩陣 無雜訊簡報 控制關注點 搭順風車 塞進對方主張 新品新店新渠道 量化數據 方案A 方案B 方案C 上中下三策 組織決策三角色 拍板人 總經理 評估人 CFO 財務總監 執行人 簡單易行",
      summary: "【無雜訊版型 5：麥肯錫論法】橫軸展開對方組織內「拍板人（決策者）→評估人（影響者）→執行人（一線窗口★）」三大角色鏈，縱軸對應「角色痛點診斷」與「順風車客製化解方」。",
      action: "針對重大提案設計 A/B/C 三套選項，並為拍板人、評估人、執行人分別客製化對應價值的說帖。",
      url: "course-tang-junjian-negotiation.html#slide-11"
    },
    {
      bookId: "course-001",
      bookTitle: "《有效提升你的談判能力》湯君健",
      slideNum: 12,
      slideId: "slide-12",
      layer: "defense",
      chapter: "第 5 講（上）離桌底氣與情緒控場（Level 1–2｜版型 6：對立論法）",
      title: "① 主張：雙贏是結果而非目的——建立「沒有非成交不可」的離桌底氣，堅持對事不對人並在失控前主動喊停",
      keywords: "版型6 對立論法 心態對比 無雜訊簡報 談判心態 沒有非成交不可 離桌底氣 雙贏是結果不是目的 短期讓步 長期關係 不平等關係 同理心 帶節奏 對事不對人 情緒斷路器 主動喊停 中場休息 負氣牌",
      summary: "【無雜訊版型 6：對立論法】沿四大心理維度正反對照「見解 A：患得患失弱勢心態（害怕破局、被帶節奏）」與「見解 B：隨時離桌強者心態（手握 BATNA、情緒斷路器冷靜控場★）」。",
      action: "會前強制書面寫下「若談崩之具體備案」與「評估對手離桌機率」各一行，並於議程預留 15 分鐘中場休會時間。",
      url: "course-tang-junjian-negotiation.html#slide-12"
    },
    {
      bookId: "course-001",
      bookTitle: "《有效提升你的談判能力》湯君健",
      slideNum: 13,
      slideId: "slide-13",
      layer: "defense",
      chapter: "第 5 講（下）五大心理戰積極防禦（Level 2 進階｜版型 5：麥肯錫論法）",
      title: "① 主張：建立談判桌上的「積極防禦」——以麥肯錫診斷矩陣精準識破虛張聲勢、切香腸、底線時間與紅白臉心理戰術",
      keywords: "版型5 麥肯錫論法 防禦矩陣 無雜訊簡報 積極防禦 五大心理戰 虛張聲勢 冷落晾人 家樂福信條 製造負罪感 真問題 偽問題 面子換裡子 軟刀子 讚揚對手 底線時間 最後期限 紅白臉雙簧 全權代表 人數對等",
      summary: "【無雜訊版型 5：麥肯錫論法】橫軸鎖定對手高頻心理戰術（虛張聲勢打壓、得寸進尺蠶食、紅白臉與假死線★），縱軸拆解「攻擊套路識別」與「看破並溫和點破之積極防禦解方」。",
      action: "回顧近期商務談判中遭遇的施壓手法，針對「底線時間」與「紅白臉」預先熟記標準反問與拆穿話術。",
      url: "course-tang-junjian-negotiation.html#slide-13"
    },
    {
      bookId: "course-001",
      bookTitle: "《有效提升你的談判能力》湯君健",
      slideNum: 14,
      slideId: "slide-14",
      layer: "posture",
      chapter: "第 6 講 ｜ 三柱姿態與標準拒絕公式（Level 2 進階｜版型 4：連鎖論法）",
      title: "① 主張：貫徹「態度誠懇、立場堅定、身段柔軟」三柱姿態，依序執行「肯定➔理由➔替代方案」三步連鎖拒絕公式",
      keywords: "版型4 連鎖論法 拒絕公式流程 無雜訊簡報 談判姿態 一致性原則 態度要誠懇 立場要堅定 身段要柔軟 理想結果 嚴禁問底線 提前對帳 點頭 眼神 微前傾 標準拒絕公式 關門指路 手掌向下按壓 雙腳種地 模糊語言 如果就",
      summary: "【無雜訊版型 4：連鎖論法】以三支柱姿態為基礎，展開「Step 1 同理肯定 ➔ Step 2 客觀理由（關門守底線）➔ Step 3 拋出如果…就…替代方案（指路促合作★）」端到端話術流程。",
      action: "針對最常被客戶或供應商挑戰的 2 項條款（如單價、交期），依「前半句關門＋後半句指路」預寫標準拒絕公式。",
      url: "course-tang-junjian-negotiation.html#slide-14"
    },
    {
      bookId: "course-001",
      bookTitle: "《有效提升你的談判能力》湯君健",
      slideNum: 15,
      slideId: "slide-15",
      layer: "synthesis",
      chapter: "跨模組整合 ｜ 八條因果鏈 × B2B 顧問式銷售（Level 3 高階｜版型 1：一對一論法）",
      title: "① 主張：串聯全課八條邏輯因果鏈並結合「MEDDIC 顧問式銷售」，使商務專案價值捕獲率躍升至 2.4 倍",
      keywords: "版型1 一對一論法 價值捕獲長條圖 無雜訊簡報 八條邏輯因果鏈 機會成本 離桌底氣 分橘子 價值鏈 MEDDIC 指標量化 Metrics 經濟決策者 EB 決策標準 內部擁護者 Champion B2B銷售 採購協同",
      summary: "【無雜訊版型 1：一對一論法】單一強證據對比五種談判段位：將佛系退讓(0.65x)、強硬爭吵(0.80x)、單純價格戰(1.0x)、條件交換(1.55x)設為灰階基準，突顯「三層整合×顧問銷售(2.40x★)」之標竿報酬。",
      action: "在大型 B2B 專案中，將 MEDDIC 角色盤點（EB/Champion）與湯君健「拍板人／評估人／執行人」說帖同步對齊。",
      url: "course-tang-junjian-negotiation.html#slide-15"
    },
    {
      bookId: "course-001",
      bookTitle: "《有效提升你的談判能力》湯君健",
      slideNum: 16,
      slideId: "slide-16",
      layer: "synthesis",
      chapter: "全課總結 ｜ 談判前一頁紙作戰畫布（Level 1–3 全員實戰｜版型 2：並列論法）",
      title: "① 主張：進場前 15 分鐘必填「目標底線・條件與價值設計・心態與語言防線」三欄並列《談判前一頁紙作戰畫布》",
      keywords: "版型2 並列論法 一頁紙畫布 無雜訊簡報 談判前一頁紙 作戰畫布 行動清單 機會成本底線 三級條款 假設提問 價值鏈三角形 拒絕公式 利益與尊重兼得",
      summary: "【無雜訊版型 2：並列論法】將全課六講收斂為三欄同構並列檢核模組：模組 A 目標與底線定位（1-2講）、模組 B 條件與價值設計★（3-4講）、模組 C 心態與語言防線（5-6講）。",
      action: "於下一場重要商務協商前，花 15 分鐘填妥「談判前一頁紙」三大並列模組帶入會議室執行。",
      url: "course-tang-junjian-negotiation.html#slide-16"
    }
  ]
};

// 相容別名，供共用檢索引擎 app.js 讀取
window.STRATEGY_PORTAL_DATA = window.NEGOTIATION_PORTAL_DATA;
