/* ==========================================================================
   商務談判協商知識庫 — 全站跨書／跨簡報頁深層檢索索引庫 (search-index.js)
   撰寫原則：整潔 (Clean) · 精準 (Precise) · 專業 (Professional)
   適用對象：Level 1 入門基礎 ➔ Level 2 進階實戰 ➔ Level 3 高階破局
   ========================================================================== */

window.NEGOTIATION_PORTAL_DATA = {
  portalMeta: {
    title: "商務談判協商知識庫暨麥肯錫簡報教材門戶",
    version: "R2.0 (2026-09)",
    system: "專業管理學院 ▸ 商務談判與協商策略知識庫",
    targetBooksCapacity: 50
  },

  /* 書籍與課程教材總表 (支援六大領域篩選與未來 50+ 本擴充) */
  books: [
    {
      id: "course-001",
      code: "COURSE #001",
      status: "published",
      domain: "framework price terms value defense posture",
      domainLabel: "01 核心框架與三層模型（L1–L3 全覆蓋）",
      title: "《有效提升你的談判能力：解決「我要」問題的實戰體系》",
      author: "湯君健（前寶潔 P&G 銷售部渠道總監、大型電商企業大學校長）",
      year: "2026 麥肯錫簡報首發",
      slidesCount: 16,
      exhibitsCount: 16,
      tablesCount: 16,
      actionsCount: 13,
      url: "course-tang-junjian-negotiation.html",
      pptxUrl: "downloads/tang-junjian-negotiation-mckinsey-briefing.pptx",
      thesis: "談判是運用決策中的理性與非理性因素，「以己方目標為先」，與對手聯手共創解決方案的過程。本教材透過「價格談判（分配博弈）→ 條件談判（多維交換）→ 價值談判（納入第三方把餅做大）」三層動態模型，結合內在心理防禦與外在語言姿態兩道防線，協助入門至進階學員實現利益與尊重兼得。",
      tags: [
        "解決我要問題",
        "分橘子冰山模型",
        "以己方目的為先",
        "價格談判",
        "條件談判",
        "價值談判",
        "機會成本底線",
        "供應鏈成本拆解",
        "報完價立刻閉嘴",
        "離桌威脅判讀",
        "遞減讓步原則",
        "條件換條件",
        "假設性提問",
        "最佳可替代方案",
        "價值鏈三角形",
        "拍板人評估人執行人",
        "離桌底氣",
        "五大心理戰防禦",
        "破解紅白臉",
        "標準拒絕公式",
        "誠懇堅定柔軟",
        "談判前一頁紙"
      ]
    },
    {
      id: "case-n01",
      code: "PLAYBOOK #N01",
      status: "published",
      domain: "value terms",
      domainLabel: "04 價值創造與組織決策（Level 3 高階）",
      title: "《B2B 複雜合約談判：三層談判模型 × MEDDIC 顧問式銷售協同》",
      author: "專業管理學院・B2B 商務實戰整合教案",
      year: "2026 實戰整合版",
      slidesCount: 2,
      exhibitsCount: 2,
      tablesCount: 2,
      actionsCount: 5,
      url: "course-tang-junjian-negotiation.html#slide-15",
      thesis: "將「一核心、三層循環、兩道防線」落地於 B2B 策略採購與大客戶銷售合約：當單價卡關時主動切換至條件層（付款期程、保固、交期），或納入第三方（終端客戶、通路、金融機構）做大價值鏈三角形，並對齊 MEDDIC 的經濟決策者（EB）、內部擁護者（Champion）與量化指標（Metrics）。",
      tags: ["B2B合約", "採購議價", "大客戶銷售", "MEDDIC整合", "談判前一頁紙", "八條邏輯因果鏈", "三級條款清單"]
    },
    {
      id: "book-002",
      code: "BOOK #002",
      status: "upcoming",
      domain: "framework terms",
      domainLabel: "01 核心框架與三層模型（Level 1–2）",
      title: "《哈佛談判課：談判力（Getting to Yes）》",
      author: "羅傑·費雪（Roger Fisher）、威廉·尤瑞（William Ury）｜哈佛談判專案",
      year: "候選教材佇列",
      slidesCount: 15,
      exhibitsCount: 15,
      tablesCount: 15,
      actionsCount: 20,
      url: "course-tang-junjian-negotiation.html#slide-09",
      thesis: "原則式談判四大支柱：① 把人與事分開（對事不對人）；② 聚焦利益而非立場（區分表面訴求與真實需求）；③ 構思互利選項；④ 堅持客觀標準（市場行情尺子），並以 BATNA（談判協議最佳替代方案）確立離桌底氣。",
      tags: ["哈佛談判課", "原則式談判", "BATNA", "對事不對人", "聚焦利益而非立場", "客觀標準"]
    },
    {
      id: "book-003",
      code: "BOOK #003",
      status: "upcoming",
      domain: "defense posture",
      domainLabel: "05 談判心態與心理防禦（Level 2–3）",
      title: "《絕不妥協：FBI 首席談判專家教你贏得任何談判（Never Split the Difference）》",
      author: "克里斯·沃斯（Chris Voss，前 FBI 國際人質談判首席專家）",
      year: "候選教材佇列",
      slidesCount: 16,
      exhibitsCount: 16,
      tablesCount: 16,
      actionsCount: 24,
      url: "course-tang-junjian-negotiation.html#slide-07",
      thesis: "反對平庸的「折衷切半」：運用戰術同理心（Tactical Empathy）、鏡像重複（Mirroring）、情緒標註（Labeling）、阿克曼議價模型（65%→85%→95%→100% 遞減讓步）與校準型問題掌握談判控場權。",
      tags: ["絕不妥協", "Chris Voss", "FBI談判", "戰術同理心", "阿克曼模型", "遞減讓步", "校準型問題"]
    },
    {
      id: "book-004",
      code: "BOOK #004",
      status: "upcoming",
      domain: "terms value",
      domainLabel: "03 條件交換與籌碼設計（Level 1–2）",
      title: "《沃頓商學院最受歡迎的談判課（Getting More）》",
      author: "史チュアート·戴蒙德（Stuart Diamond，沃頓商學院名師）",
      year: "候選教材佇列",
      slidesCount: 15,
      exhibitsCount: 15,
      tablesCount: 15,
      actionsCount: 20,
      url: "course-tang-junjian-negotiation.html#slide-08",
      thesis: "以目標為最高導向（以己方目的為先）：挖掘對方腦中的畫面與真實顧慮，執行「己方低成本 × 對方高價值」的不等價交換，將巨大分歧拆解為漸進式共識。",
      tags: ["沃頓商學院談判課", "Stuart Diamond", "不等價交換", "目標導向", "條件交換"]
    },
    {
      id: "book-005",
      code: "BOOK #005",
      status: "upcoming",
      domain: "price defense",
      domainLabel: "02 價格博弈與報價策略（Level 2）",
      title: "《優勢談判（Secrets of Power Negotiating）》",
      author: "羅傑·道森（Roger Dawson，國際商業談判專家）",
      year: "候選教材佇列",
      slidesCount: 16,
      exhibitsCount: 16,
      tablesCount: 16,
      actionsCount: 22,
      url: "course-tang-junjian-negotiation.html#slide-06",
      thesis: "價格博弈實戰法則：高報價錨定效應、絕不接受首次報價、聞價色變（Flinch）、扮演不情願的買賣方、更高權威原則（請示主管）以及拆解紅白臉陷阱。",
      tags: ["優勢談判", "Roger Dawson", "開高價錨定", "不情願讓步", "更高權威", "紅白臉應對"]
    }
  ],

  /* 逐頁簡報全索引 (支援全站關鍵字即時檢索、螢光高亮與一鍵直達) */
  slides: [
    {
      bookId: "course-001",
      bookTitle: "《有效提升你的談判能力》湯君健",
      slideNum: 1,
      slideId: "slide-01",
      layer: "overview",
      chapter: "發刊詞 ｜ 核心定義與專家特質（Level 1 入門）",
      title: "談判是幫你解決「我要」的問題：運用決策中的理性與非理性因素，以己方目標為先並與對手聯手共創方案",
      keywords: "發刊詞 湯君健 我要的問題 利益衝突 資源有限 零和分配 吵架 軟柿子 無端妥協 理性與非理性 以己方目的為先 聯手找到解決方案 可靠 原則性強 守信 寶潔 渠道總監 電商企業大學校長 甲方 乙方 入門基礎",
      summary: "凡是「我要」、但無法輕易從他人處直接取得的目標（購車議價、房產交易、職場談薪、跨部門協商），皆屬談判範疇。缺乏談判能力易陷入兩極誤區：衝突升級導致破局，或懼怕衝突淪為「軟柿子」。頂尖談判者的核心特質是「可靠」（守原則、重信譽、專注找方案、換位思考）。",
      action: "盤點並寫下本季 3 項「我要但不易直接取得」的關鍵目標（對客戶、對供應商、對內部跨部門各一項），作為實戰演練標的。",
      url: "course-tang-junjian-negotiation.html#slide-01"
    },
    {
      bookId: "course-001",
      bookTitle: "《有效提升你的談判能力》湯君健",
      slideNum: 2,
      slideId: "slide-02",
      layer: "overview",
      chapter: "全課架構 ｜ 一核心、三層循環、兩道防線（Level 1–3）",
      title: "全課戰略骨架：以「我要」為核心，串聯價格、條件、價值三層循環模型，並由心態與姿態築起兩道防線",
      keywords: "全課架構 一核心 三層循環 兩道防線 價格談判 條件談判 交換類談判 價值談判 心態 心理戰 語言 肢體語言 循環模型 作戰階段對照表",
      summary: "全課程濃縮為「一核心（以我要為先）、三層動態循環（L1價格→L2條件→L3價值→做大餅後回歸L1價格分配）、兩道防線（內在心理防禦與外在語言姿態一致性）」。涵蓋進場準備、資訊刺探、讓步交換與僵局破冰四大標準作戰階段。",
      action: "在進入商務協商前，先以「三層模型」診斷當前談判所處維度，並利用「談判前一頁紙」完成全方位備戰。",
      url: "course-tang-junjian-negotiation.html#slide-02"
    },
    {
      bookId: "course-001",
      bookTitle: "《有效提升你的談判能力》湯君健",
      slideNum: 3,
      slideId: "slide-03",
      layer: "foundation",
      chapter: "第 1 講（上）表面訴求 vs 真實需求（Level 1 入門）",
      title: "第 1 講（上）表面訴求不等於真實需求：堅守「以己方目的為先」，透過資訊交換與加工挖掘對方的「橘子皮」",
      keywords: "分橘子 冰山模型 橘子皮 小橘燈 橘子肉 橘子汁 表面訴求 真實需求 三要點 以己方目的為先 向前爭取 理性與非理性 7項準備清單 座位安排 靠牆 靠門 壓迫感 資訊交換 資訊加工 潛台詞",
      summary: "分橘子案例揭示：雙方表面爭奪 5 顆橘子數量（零和），實則一方要果肉榨汁、一方要果皮做燈，皮肉分離即可各自取得 100% 所需。談判三大要點：①以己方目的為先（向前爭取）；②併用理性與非理性（含需求、利益、性格、議程、靠牆座位配置等 7 項清單）；③聯手找方案（資訊交換＋換位加工）。",
      action: "會前拆解對手的「表面立場」與「背後真實用途（橘子皮）」，並將對手性格與主客座位配置納入準備流程。",
      url: "course-tang-junjian-negotiation.html#slide-03"
    },
    {
      bookId: "course-001",
      bookTitle: "《有效提升你的談判能力》湯君健",
      slideNum: 4,
      slideId: "slide-04",
      layer: "foundation",
      chapter: "第 1 講（下）三種基本模型與跨層切換（Level 1 入門）",
      title: "第 1 講（下）複雜談判皆可拆解為三種基本模型：先辨識所處層次，並在卡關時主動推動談判跨層升級",
      keywords: "三種基本模型 價格談判 零和博弈 條件談判 付款方式 交期 良率 各取所需 價值談判 創造新價值 孩子看電視 跨層切換 外事人員標準13條 美國國務院 外交官",
      summary: "談判由簡入繁分為三類：①價格談判（單維度零和分配）；②條件談判（多維度條款互換、各取所需）；③價值談判（共同投入資源創造增量價值）。當價格僵持不下時，應主動切換至條件層；當把餅做大後，仍須回歸價格層完成分配。",
      action: "檢視近期進行中的商務協商，診斷其目前處於價格、條件或價值哪一層，並規劃跨層升級方案。",
      url: "course-tang-junjian-negotiation.html#slide-04"
    },
    {
      bookId: "course-001",
      bookTitle: "《有效提升你的談判能力》湯君健",
      slideNum: 5,
      slideId: "slide-05",
      layer: "price",
      chapter: "第 2 講（上）機會成本底線與成本拆解（Level 1–2）",
      title: "第 2 講（上）善戰者立於不敗之地：以機會成本設定底線、以市場尺子錨定目標，並拆解供應鏈成本做到「真正懂行」",
      keywords: "價格談判 準備階段 底線價 心理最低價 機會成本 目標價 市場尺子 二手車 真正懂行 零售巨頭 首席商品官 紅酒採購 成本拆解 Should-Cost 孫子兵法 善戰者立於不敗之地 薪資基數",
      summary: "價格談判準備三大基石：①底線價＝心理最低價或手頭備選方案之「機會成本」（如已有 12.5 元買家，底線即鎖定 12.5 元）；②目標價＝以市場行情為客觀尺子，設定努力可及高標並附支撐理由；③供應鏈成本拆解：如零售巨頭採購拆解紅酒產地、包材、儲運與合理毛利，直接剔除虛高水分。",
      action: "橫向比對 5 家以上供應商報價單，拆解原材料、加工、物流與毛利結構，並在會前書面確立底線價與目標價。",
      url: "course-tang-junjian-negotiation.html#slide-05"
    },
    {
      bookId: "course-001",
      bookTitle: "《有效提升你的談判能力》湯君健",
      slideNum: 6,
      slideId: "slide-06",
      layer: "price",
      chapter: "第 2 講（中）報價先後手與沉默鐵律（Level 2 進階）",
      title: "第 2 講（中）掌握報價主動權：依資訊對稱度決定先後手，靈活選用高報價或合理報價，並嚴格執行「報完價立刻閉嘴」",
      keywords: "誰先報價 資訊不對稱 後出價 掌握行情 先報價 錨定效應 高報價 還價空間 五星飯店 會務銷售 給面子 合理報價 報價理由 報完價立刻閉嘴 沉默 察言觀色 心虛解釋",
      summary: "先後手決策：不熟行情、資訊不對稱時讓對方先報；比對方更懂行情時大膽先報以錨定預期。高報價（上浮 5%～100%）可預留砍價空間讓對方高層有面子，但不適用於對手極懂行、長期夥伴、行情看跌或急需走量。通用鐵律：報價前充分陳述 1234 理由，報出數字後立刻閉嘴沉默觀察反應。",
      action: "為下一筆關鍵報價預先寫妥 3 條客觀理由，並在會議中報出數字後強制默數 5 秒不發一言。",
      url: "course-tang-junjian-negotiation.html#slide-06"
    },
    {
      bookId: "course-001",
      bookTitle: "《有效提升你的談判能力》湯君健",
      slideNum: 7,
      slideId: "slide-07",
      layer: "price",
      chapter: "第 2 講（下）離桌威脅判讀與遞減讓步（Level 2 進階）",
      title: "第 2 講（下）掌控還價拉鋸戰：從「具體使用場景挑刺」識破假離桌威脅，並做幅度遞減的「不情願讓步者」",
      keywords: "還價 拆解依據 離桌威脅 假離桌 真離桌 具體使用場景 非硬傷 房間擺床 座椅靠背 一言不發 讓步三紀律 不一步到位 不情願的讓步者 幅度遞減 先讓50再讓80 得寸進尺",
      summary: "面對籠統高價應要求對方拆解計算依據。判讀「離桌威脅」：若對手挑剔細節帶有「具體使用場景」且非致命硬傷（如嫌房間擺床略擠、座椅略硬），代表心理已代入成交後畫面，成交意願極高；真想放棄者往往一言不發離場。讓步三大紀律：①不一步到位、②表現不情願、③幅度嚴格遞減（如 50→25→5，嚴禁先讓 50 再讓 80）。",
      action: "會前預先規劃 3 次遞減讓步階梯（如 3% → 1.5% → 0.5%），並觀察對手挑刺是否具備具體使用場景以判讀成交意願。",
      url: "course-tang-junjian-negotiation.html#slide-07"
    },
    {
      bookId: "course-001",
      bookTitle: "《有效提升你的談判能力》湯君健",
      slideNum: 8,
      slideId: "slide-08",
      layer: "terms",
      chapter: "第 3 講（上）條款三級分類與假設提問（Level 2 進階）",
      title: "第 3 講（上）「條款列得多」等同價格開得高：將可談條件分為三級目標，並以非正式會議與假設性提問刺探真實優先序",
      keywords: "條件談判 條款三級分類 商鋪租賃 20項清單 主要目標 次要目標 底線條件 非正式會議 吹風會 需求確認類問題 優先級排序 假設性問題 二選一 期權 薪資 傾聽原則",
      summary: "條款列得越細，手上的讓步緩衝池就越大。將合約條款分為三級：①主要目標（核心必保）、②次要目標（可讓步交換籌碼）、③底線條件（破局紅線）。透過中層「非正式會議（吹風會）」、需求確認排序題與「二選一假設性問題」（如低底薪配期權 vs 高底薪無期權），精準探出對手真實優先序。",
      action: "將標準商務合約拆解為 15～20 項條款並完成三級標註；會前準備 2 道二選一假設題以測試對手真實偏好。",
      url: "course-tang-junjian-negotiation.html#slide-08"
    },
    {
      bookId: "course-001",
      bookTitle: "《有效提升你的談判能力》湯君健",
      slideNum: 9,
      slideId: "slide-09",
      layer: "terms",
      chapter: "第 3 講（下）最佳可替代方案與條件交換（Level 2 進階）",
      title: "第 3 講（下）以己方低成本條件換取對方高價值讓步：尋找優於談崩的最佳可替代方案，並嚴守「條件換條件」原則",
      keywords: "最佳可替代方案 顧慮替換法 名貴木桌 隱藏可替代方案 BATNA 談崩退路 不等價交換 讓步三原則 次要目標讓步 以退為進 不情願讓步 更高權威 條件換條件 付三押三 換新空調 防禦緩衝帶",
      summary: "遇到不可接受之苛刻條款時，深挖背後真實顧慮並以低成本方案替換（如房東要求年付是怕損壞名貴木桌→請其搬走木桌維持季付）。「最佳可替代方案」指以我方低成本高收益 A 條件置換對方低成本高收益 B 條件（隱藏替代方案則為談崩退路 BATNA）。讓步三原則：讓在次要目標、扮演不情願讓步者（請示主管）、堅持條件換條件（答應押三但要求換新空調作為防禦緩衝帶）。",
      action: "每次被迫讓步時務必掛鉤一項新條件作為「防禦緩衝帶」（例：單價降 2% 可以，但預付款須提高至 30%）。",
      url: "course-tang-junjian-negotiation.html#slide-09"
    },
    {
      bookId: "course-001",
      bookTitle: "《有效提升你的談判能力》湯君健",
      slideNum: 10,
      slideId: "slide-10",
      layer: "value",
      chapter: "第 4 講（上）價值鏈三角形與增量破局（Level 3 高階）",
      title: "第 4 講（上）僵局是價值談判的最佳入口：跳出雙邊零和底邊，將第三方（顧客）納入價值鏈三角形以擴大總利潤面積",
      keywords: "價值談判 創造新價值 僵局破冰 手機採購 10元價差 總利潤額 利潤率 女性顧客 女性專屬手機 流量購物節 閱讀價值鏈 第三方 終端顧客 價值鏈三角形 求職談薪",
      summary: "當雙方預算與底價毫無交集時，應跳出「供應商—採購方」零和底邊，認清商業追求的是總「利潤額」而非帳面「利潤率」。將第三方（終端顧客）納入頂點構成「價值鏈三角形」，如電商平台針對女性客群與手機廠共推女性專機並搭配購物節流量，使銷量與總利潤額雙創紀錄。",
      action: "挑選一項價格卡關的合作專案，繪製納入終端顧客或金融機構之「價值鏈三角形」，並試算增量收益空間。",
      url: "course-tang-junjian-negotiation.html#slide-10"
    },
    {
      bookId: "course-001",
      bookTitle: "《有效提升你的談判能力》湯君健",
      slideNum: 11,
      slideId: "slide-11",
      layer: "value",
      chapter: "第 4 講（下）順風車提案與決策三角色（Level 3 高階）",
      title: "第 4 講（下）把己方方案「塞進對方的主張裡」：以量化數據、A/B/C 三選項與決策鏈三角色精準攻克組織決策",
      keywords: "控制關注點 搭順風車 塞進對方主張 新品新店新渠道 量化數據 方案A 方案B 方案C 上中下三策 組織決策三角色 拍板人 總經理 評估人 CFO 財務總監 執行人 簡單易行",
      summary: "價值共創需雙方投入資源，必須先探詢對方年度戰略，將己方提案「塞進他的主張裡」搭順風車。說服組織三大關鍵：①用嚴謹數據算清利益；②提供 A（快見效高投入）、B（穩健）、C（低風險試水）三套選項；③分眾擊破三角色：對拍板人（總經理）講戰略與總利潤、對評估人（CFO/骨幹）講嚴謹財務模型、對執行人（窗口）提供簡單易行 SOP。",
      action: "針對重大提案設計 A/B/C 三套選項，並為拍板人、評估人、執行人分別客製化對應價值的說帖。",
      url: "course-tang-junjian-negotiation.html#slide-11"
    },
    {
      bookId: "course-001",
      bookTitle: "《有效提升你的談判能力》湯君健",
      slideNum: 12,
      slideId: "slide-12",
      layer: "defense",
      chapter: "第 5 講（上）離桌底氣與情緒控場（Level 1–2）",
      title: "第 5 講（上）雙贏是結果而非目的：建立「沒有非成交不可」的離桌底氣，堅持對事不對人並在失控前主動喊停",
      keywords: "談判心態 沒有非成交不可 離桌底氣 雙贏是結果不是目的 短期讓步 長期關係 不平等關係 同理心 帶節奏 對事不對人 情緒斷路器 主動喊停 中場休息 負氣牌",
      summary: "心態四大支柱：①沒有非成交不可的談判（你的替代方案越少，對手條件越苛刻）；②雙贏是結果而非目的（過於融洽會喪失價值創造機會，短期無端讓步只會換來不平等關係）；③駕馭同理心、堅持對事不對人，不被對手帶節奏；④設置情緒斷路器：當己方焦慮或對手失控時，立即主動提議中場休息喊停。",
      action: "會前強制書面寫下「若談崩之具體備案」與「評估對手離桌機率」各一行，並於議程預留 15 分鐘中場休會時間。",
      url: "course-tang-junjian-negotiation.html#slide-12"
    },
    {
      bookId: "course-001",
      bookTitle: "《有效提升你的談判能力》湯君健",
      slideNum: 13,
      slideId: "slide-13",
      layer: "defense",
      chapter: "第 5 講（下）五大心理戰積極防禦（Level 2 進階）",
      title: "第 5 講（下）建立談判桌上的「積極防禦」：精準識破虛張聲勢、製造負罪感、面子換裡子、底線時間與紅白臉五大心理戰術",
      keywords: "積極防禦 五大心理戰 虛張聲勢 冷落晾人 家樂福信條 製造負罪感 真問題 偽問題 面子換裡子 軟刀子 讚揚對手 底線時間 最後期限 紅白臉雙簧 全權代表 人數對等",
      summary: "五大心理戰反制法則：①虛張聲勢（晾人1小時、高管排場）→秉持家樂福信條「大名片背後常是普通銷售」，衣著嚴謹專注條款；②製造負罪感（放大瑕疵）→區分真問題（正面解決拉回主題）與偽問題（微笑帶過）；③面子換裡子（給台階軟刀子）→致謝但死守底線，會後讚揚對手；④底線時間（三天期限）→反問「為何三天？誰給您時間壓力？」；⑤紅白臉→直接點破並要求指定全權代表，確保人數對等。",
      action: "回顧近期商務談判中遭遇的施壓手法，針對「底線時間」與「紅白臉」預先熟記標準反問與拆穿話術。",
      url: "course-tang-junjian-negotiation.html#slide-13"
    },
    {
      bookId: "course-001",
      bookTitle: "《有效提升你的談判能力》湯君健",
      slideNum: 14,
      slideId: "slide-14",
      layer: "posture",
      chapter: "第 6 講 ｜ 三柱姿態與標準拒絕公式（Level 2 進階）",
      title: "第 6 講 以不變應萬變的談判姿態：貫徹「態度誠懇、立場堅定、身段柔軟」，善用拒絕公式與「如果…就…」開啟雙向交換",
      keywords: "談判姿態 一致性原則 態度要誠懇 立場要堅定 身段要柔軟 理想結果 嚴禁問底線 提前對帳 點頭 眼神 微前傾 標準拒絕公式 關門指路 手掌向下按壓 雙腳種地 模糊語言 如果就",
      summary: "語言與肢體必須與姿態高度一致：①態度要誠懇：探詢「理想結果」（嚴禁問底線）、展示會前準備；點頭、眼神接觸、身體微前傾、雙手攤開。②立場要堅定：運用「標準拒絕公式」（前半句關門守底線＋後半句指路提新方案）；手掌向下按壓控場、雙腳如種在地面般穩固。③身段要柔軟：以模糊語言潤滑、用「如果…就…」取代威脅；肩頸放鬆、微笑平和反駁。",
      action: "針對最常被客戶或供應商挑戰的 2 項條款（如單價、交期），依「前半句關門＋後半句指路」預寫標準拒絕公式。",
      url: "course-tang-junjian-negotiation.html#slide-14"
    },
    {
      bookId: "course-001",
      bookTitle: "《有效提升你的談判能力》湯君健",
      slideNum: 15,
      slideId: "slide-15",
      layer: "synthesis",
      chapter: "跨模組整合 ｜ 八條因果鏈 × B2B 顧問式銷售（Level 3 高階）",
      title: "跨模組深度整合：串聯全課八條邏輯因果鏈，並將「三層談判模型」與「MEDDIC 顧問式銷售」無縫對接",
      keywords: "八條邏輯因果鏈 機會成本 離桌底氣 分橘子 價值鏈 MEDDIC 指標量化 Metrics 經濟決策者 EB 決策標準 內部擁護者 Champion B2B銷售 採購協同",
      summary: "串聯全課八條橫向因果鏈（機會成本備案支撐離桌底氣；深挖真實需求驅動條件交換與價值鏈擴張；讓步紀律與心理防線外顯為三柱姿態），並與 B2B 顧問式銷售（MEDDIC）無縫結合：前段以 Metrics 量化與 EB/Champion 角色鎖定控盤，後段以三層談判模型收官。",
      action: "在大型 B2B 專案中，將 MEDDIC 角色盤點（EB/Champion）與湯君健「拍板人／評估人／執行人」說帖同步對齊。",
      url: "course-tang-junjian-negotiation.html#slide-15"
    },
    {
      bookId: "course-001",
      bookTitle: "《有效提升你的談判能力》湯君健",
      slideNum: 16,
      slideId: "slide-16",
      layer: "synthesis",
      chapter: "全課總結 ｜ 談判前一頁紙作戰畫布（Level 1–3 全員實戰）",
      title: "全課總結與落地工具：將「替代方案、條款三級分類、底線與拒絕公式」收斂為「談判前一頁紙」，實現利益與尊重兼得",
      keywords: "談判前一頁紙 作戰畫布 行動清單 機會成本底線 三級條款 假設提問 價值鏈三角形 拒絕公式 利益與尊重兼得",
      summary: "將全課六講核心工具收斂為進場前 15 分鐘必填之「談判前一頁紙（One-Page Negotiation Canvas）」五格畫布：①目標、底線（機會成本）與談崩退路；②合約條款三級分類（主要／次要／底線）；③對方深層需求與 2 道假設題；④價值鏈三角形與 A/B/C 三方案（對應三角色）；⑤報價沉默紀律、心理防禦與預寫拒絕公式。",
      action: "於下一場重要商務協商前，花 15 分鐘填妥「談判前一頁紙」五格畫布帶入會議室執行。",
      url: "course-tang-junjian-negotiation.html#slide-16"
    }
  ]
};

// 相容別名，供共用檢索引擎 app.js 讀取
window.STRATEGY_PORTAL_DATA = window.NEGOTIATION_PORTAL_DATA;
